title: Shana Deane
email: shanadeane77@gmail.com
description: Consulting & Coaching
linkedin_username: shanadeane
# facebook_username: TO DO
# twitter_username: TO DO
# youtube_username: TO DO

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include:
  - /public/
