title: Shana Deane
email: shanadeane77@gmail.com
description: Consulting and coaching
linkedin_username: shanadeane

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include:
  - /public/
